<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name: 'tarefas'
    Assistente:
        name: 'assistente'
    Tutorial:
        name: 'tutorial'
    
    
<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:root.width*0.25,root.height*0.1
        spacing:'30dp'
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                size:self.size
                pos:self.pos
                source:'moldura.png'
        Image:
            source:'logo.png'
            size_hint_y:4
            allow_stretch:True
        Botao:
            text:'Lista de Tarefas'
            on_release:app.root.current = 'tarefas'
            cor:0.4,0.1,0.8,1
        Botao:
            text:'Assistente'
            on_release:app.root.current = 'assistente'
            cor:0.4,0.1,0.8,1
        Botao:
            text:'Tutorial'
            on_release:app.root.current = 'tutorial'
            cor:0.4,0.1,0.8,1
        Botao:
            text:'Sair'
            on_release:root.confirmacao()
            cor:0.4,0.1,0.8,1

<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:'40sp'
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('tarefas').removeWidget(root)

<Assistente>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Assistente virtual'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'>'
                size_hint_x:None
                width:'40sp'
                on_release:root.mensagem(texto.text)
<Tutorial>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tutorial'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        Label:
            id:label
            font_size:'22sp'
            text: 'A assistente MK é uma assistente virtual capaz de fazer operações matemáticas, conversar,\nabrir seus programas e sites favoritos, entre outras funcionalidades...:'
        Label:
            id:label
            font_size:'22sp'
            text: 'Como usar a assistente MK: \nPara que a assistente possa abrir um programa para você, você digita aprende no chat,\npassa como irá solicitar esse comando, posteriomente executar e o caminho do \nexecutável do programa ou o site desejado.'
        Image:
            source:'tutorial.png'
            height: 200
            allow_stretch:True